name: weather
description: Weather fetch api using MobX



publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7


flutter:

  uses-material-design: true


  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
